CREATE TABLE [dbo].[Attachment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Filename] NVARCHAR(500) UNIQUE,
	[CreatedAt] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] SMALLDATETIME NULL
)
