CREATE TABLE [dbo].[Contract] 
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Salary] DECIMAL(19,4) NOT NULL,
	[StartDate] DATE NOT NULL,
	[ExpireDate] DATE,
	[StatusId] INT FOREIGN KEY REFERENCES [Status](Id) NOT NULL,
	[CreatedAt] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] SMALLDATETIME NULL
)