CREATE TABLE [dbo].[Organization]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[OrganizationName] NVARCHAR(50) NOT NULL UNIQUE,
	[PhotoPath] NVARCHAR(75),
	[CreatedAt] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] SMALLDATETIME NULL
)
